%define debug_package %{nil}
# Generated by go2rpm 1.16.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/cretz/bine
%global goihead bine
%global goipath github.com/cretz/%{goihead}

Version:  0.2.0

%gometa -L -f


%global common_description %{expand:
Go library for accessing and embedding Tor clients and servers.}

%global golicenses      LICENSE
%global godocs          examples README.md torutil/geoipembed/README.md

Name:           golang-github-cretz-bine
Release:        %autorelease
Summary:        Go library for accessing and embedding Tor clients and servers

License:        MIT
URL:            %{gourl}

Source0: https://%{goipath}/archive/v%{version}/%{goihead}-%{version}.tar.gz

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
rm -rfv process/embedded

%install
%gopkginstall

%gopkgfiles

%changelog
%autochangelog
